[font]
size = 9.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"





# Nightfox Alacritty Colors
## name: terafox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/alacritty.toml



