# host
https://httpbin.org:443
# curl options
--silent



# headers
Accept: application/json
Content-Type: application/json
Connection: keep-alive
User-Agent: VRC



# request get
GET /anything

# # request post
# POST /anything
# {
#   "name": "John Doe",
#   "age": 25
#     "method": "POST",
# }

# request put
# PUT /anything
# {
#   "name": "John Doe",
#   "age": 25
# }


